-- Phase: Drop contact identity and UTM columns now that contact_id is canonical

-- Drop dependent views first
DROP VIEW IF EXISTS source_attribution_summary;
DROP VIEW IF EXISTS deprecated_mappings_summary;
DROP VIEW IF EXISTS attribution_monitoring;

-- Appointments: remove contact identity and attribution fields
ALTER TABLE appointments 
  DROP COLUMN IF EXISTS contact_name,
  DROP COLUMN IF EXISTS email,
  DROP COLUMN IF EXISTS phone,
  DROP COLUMN IF EXISTS contact_source,
  DROP COLUMN IF EXISTS contact_utm_source,
  DROP COLUMN IF EXISTS contact_utm_medium,
  DROP COLUMN IF EXISTS contact_utm_campaign,
  DROP COLUMN IF EXISTS contact_utm_content,
  DROP COLUMN IF EXISTS contact_referrer,
  DROP COLUMN IF EXISTS contact_gclid,
  DROP COLUMN IF EXISTS contact_fbclid,
  DROP COLUMN IF EXISTS contact_campaign_id,
  DROP COLUMN IF EXISTS last_attribution_source,
  DROP COLUMN IF EXISTS utm_source,
  DROP COLUMN IF EXISTS utm_medium,
  DROP COLUMN IF EXISTS utm_campaign,
  DROP COLUMN IF EXISTS utm_content,
  DROP COLUMN IF EXISTS utm_term,
  DROP COLUMN IF EXISTS utm_id,
  DROP COLUMN IF EXISTS fbclid,
  DROP COLUMN IF EXISTS fbc,
  DROP COLUMN IF EXISTS fbp,
  DROP COLUMN IF EXISTS landing_url,
  DROP COLUMN IF EXISTS session_source,
  DROP COLUMN IF EXISTS medium_id,
  DROP COLUMN IF EXISTS user_agent,
  DROP COLUMN IF EXISTS ip_address,
  DROP COLUMN IF EXISTS attribution_data,
  DROP COLUMN IF EXISTS last_attribution_data;

-- Discoveries: remove contact identity and any UTM/attribution fields if present
ALTER TABLE discoveries 
  DROP COLUMN IF EXISTS contact_name,
  DROP COLUMN IF EXISTS email,
  DROP COLUMN IF EXISTS phone,
  DROP COLUMN IF EXISTS contact_source,
  DROP COLUMN IF EXISTS contact_utm_source,
  DROP COLUMN IF EXISTS contact_utm_medium,
  DROP COLUMN IF EXISTS contact_utm_campaign,
  DROP COLUMN IF EXISTS contact_utm_content,
  DROP COLUMN IF EXISTS contact_referrer,
  DROP COLUMN IF EXISTS contact_gclid,
  DROP COLUMN IF EXISTS contact_fbclid,
  DROP COLUMN IF EXISTS contact_campaign_id,
  DROP COLUMN IF EXISTS last_attribution_source,
  DROP COLUMN IF EXISTS utm_source,
  DROP COLUMN IF EXISTS utm_medium,
  DROP COLUMN IF EXISTS utm_campaign,
  DROP COLUMN IF EXISTS utm_content,
  DROP COLUMN IF EXISTS utm_term,
  DROP COLUMN IF EXISTS utm_id,
  DROP COLUMN IF EXISTS fbclid,
  DROP COLUMN IF EXISTS fbc,
  DROP COLUMN IF EXISTS fbp,
  DROP COLUMN IF EXISTS landing_url,
  DROP COLUMN IF EXISTS session_source,
  DROP COLUMN IF EXISTS medium_id,
  DROP COLUMN IF EXISTS user_agent,
  DROP COLUMN IF EXISTS ip_address,
  DROP COLUMN IF EXISTS attribution_data,
  DROP COLUMN IF EXISTS last_attribution_data;

-- Dials: remove contact identity and UTM/attribution mirrors
ALTER TABLE dials 
  DROP COLUMN IF EXISTS contact_name,
  DROP COLUMN IF EXISTS email,
  DROP COLUMN IF EXISTS phone,
  DROP COLUMN IF EXISTS contact_source,
  DROP COLUMN IF EXISTS contact_utm_source,
  DROP COLUMN IF EXISTS contact_utm_medium,
  DROP COLUMN IF EXISTS contact_utm_campaign,
  DROP COLUMN IF EXISTS contact_utm_content,
  DROP COLUMN IF EXISTS contact_referrer,
  DROP COLUMN IF EXISTS contact_gclid,
  DROP COLUMN IF EXISTS contact_fbclid,
  DROP COLUMN IF EXISTS contact_campaign_id,
  DROP COLUMN IF EXISTS last_attribution_source,
  DROP COLUMN IF EXISTS utm_source,
  DROP COLUMN IF EXISTS utm_medium,
  DROP COLUMN IF EXISTS utm_campaign,
  DROP COLUMN IF EXISTS utm_content,
  DROP COLUMN IF EXISTS utm_term,
  DROP COLUMN IF EXISTS utm_id,
  DROP COLUMN IF EXISTS fbclid,
  DROP COLUMN IF EXISTS fbc,
  DROP COLUMN IF EXISTS fbp,
  DROP COLUMN IF EXISTS landing_url,
  DROP COLUMN IF EXISTS session_source,
  DROP COLUMN IF EXISTS medium_id,
  DROP COLUMN IF EXISTS user_agent,
  DROP COLUMN IF EXISTS ip_address,
  DROP COLUMN IF EXISTS attribution_data,
  DROP COLUMN IF EXISTS last_attribution_data; 